<?php
// Generated by ZF's ./bin/classmap_generator.php
return array(
    'HumusMvcAssetManager\Service\AssetManagerServiceFactory' => dirname(__FILE__) . '//src/HumusMvcAssetManager/Service/AssetManagerServiceFactory.php',
    'HumusMvcAssetManager\Service\AssetManager'               => dirname(__FILE__) . '//src/HumusMvcAssetManager/Service/AssetManager.php',
    'HumusMvcAssetManager\Exception\ExceptionInterface'       => dirname(__FILE__) . '//src/HumusMvcAssetManager/Exception/ExceptionInterface.php',
    'HumusMvcAssetManager\Exception\RuntimeException'         => dirname(__FILE__) . '//src/HumusMvcAssetManager/Exception/RuntimeException.php',
    'HumusMvcAssetManager\Module'                             => dirname(__FILE__) . '//src/HumusMvcAssetManager/Module.php',
);